package com.github.tehArchitecht.logic;

public enum Status {
    // isNameInUse
    IS_NAME_IN_USE_SUCCESS, IS_NAME_IN_USE_FAILURE_INTERNAL_ERROR,
    // signUp
    SIGN_UP_SUCCESS, SIGN_UP_FAILURE_INTERNAL_ERROR,
    // signIn
    SIGN_IN_SUCCESS, SIGN_IN_FAILURE_WRONG_DATA, SIGN_IN_FAILURE_INTERNAL_ERROR,
    // getUserOperations
    GET_USER_OPERATIONS_SUCCESS, GET_USER_OPERATIONS_FAILURE_INTERNAL_ERROR,
    // getUserAccounts
    GET_USER_ACCOUNTS_SUCCESS, GET_USER_ACCOUNTS_FAILURE_INTERNAL_ERROR,
    // userHasAccounts
    USER_HAS_ACCOUNTS_SUCCESS, USER_HAS_ACCOUNTS_FAILURE_INTERNAL_ERROR,
    // createAccount
    CREATE_ACCOUNT_SUCCESS, CREATE_ACCOUNT_FAILURE_INTERNAL_ERROR,
    // depositFunds
    DEPOSIT_FUNDS_SUCCESS, DEPOSIT_FUNDS_FAILURE_INVALID_ACCOUNT_ID, DEPOSIT_FUNDS_FAILURE_INTERNAL_ERROR,
    DEPOSIT_FUNDS_FAILURE_UNAUTHORIZED_ACCESS,
    // transferFunds
    TRANSFER_FUNDS_SUCCESS, TRANSFER_FUNDS_FAILURE_INVALID_ACCOUNT_ID, TRANSFER_FUNDS_FAILURE_INVALID_PHONE_NUMBER,
    TRANSFER_FUNDS_FAILURE_RECEIVER_HAS_NO_ACCOUNTS, TRANSFER_FUNDS_FAILURE_INSUFFICIENT_FUNDS,
    TRANSFER_FUNDS_FAILURE_INTERNAL_ERROR, TRANSFER_FUNDS_FAILURE_UNAUTHORIZED_ACCESS,
    // tokens
    BAD_TOKEN,
    // statuses used by helper methods
    SUCCESS, INVALID_ACCOUNT_ID, INTERNAL_ERROR, UNAUTHORIZED_ACCESS
}
